export enum StatType {
  NULL = 'NULL',
  STR = 'STR',
  DEX = 'DEX',
  INT = 'INT',
  LUK = 'LUK',
  HP = 'HP',
  XENON = 'XENON',
}

export interface JobData {
  name: string;
  mainStat: StatType;
}

// 메이플스토리 공식홈페이지 월드 랭킹 기준 정렬
// 카인 이후는 맨 아래 추가
export const jobs: JobData[] = [
  { name: '초보자', mainStat: StatType.NULL },
  { name: '검사', mainStat: StatType.STR },
  { name: '파이터', mainStat: StatType.STR },
  { name: '페이지', mainStat: StatType.STR },
  { name: '스피어맨', mainStat: StatType.STR },
  { name: '크루세이더', mainStat: StatType.STR },
  { name: '나이트', mainStat: StatType.STR },
  { name: '버서커', mainStat: StatType.STR },
  { name: '히어로', mainStat: StatType.STR },
  { name: '팔라딘', mainStat: StatType.STR },
  { name: '다크나이트', mainStat: StatType.STR },
  { name: '매지션', mainStat: StatType.INT },
  { name: '위자드(불,독)', mainStat: StatType.INT },
  { name: '위자드(썬,콜)', mainStat: StatType.INT },
  { name: '클레릭', mainStat: StatType.INT },
  { name: '메이지(불,독)', mainStat: StatType.INT },
  { name: '메이지(썬,콜)', mainStat: StatType.INT },
  { name: '프리스트', mainStat: StatType.INT },
  { name: '아크메이지(불,독)', mainStat: StatType.INT },
  { name: '아크메이지(썬,콜)', mainStat: StatType.INT },
  { name: '비숍', mainStat: StatType.INT },
  { name: '아처', mainStat: StatType.DEX },
  { name: '헌터', mainStat: StatType.DEX },
  { name: '사수', mainStat: StatType.DEX },
  { name: '레인저', mainStat: StatType.DEX },
  { name: '저격수', mainStat: StatType.DEX },
  { name: '보우마스터', mainStat: StatType.DEX },
  { name: '신궁', mainStat: StatType.DEX },
  { name: '아처(패스파인더)', mainStat: StatType.DEX },
  { name: '에인션트아처', mainStat: StatType.DEX },
  { name: '체이서', mainStat: StatType.DEX },
  { name: '패스파인더', mainStat: StatType.DEX },
  { name: '로그', mainStat: StatType.LUK },
  { name: '어쌔신', mainStat: StatType.LUK },
  { name: '시프', mainStat: StatType.LUK },
  { name: '허밋', mainStat: StatType.LUK },
  { name: '시프마스터', mainStat: StatType.LUK },
  { name: '나이트로드', mainStat: StatType.LUK },
  { name: '섀도어', mainStat: StatType.LUK },
  { name: '세미듀어러', mainStat: StatType.LUK },
  { name: '듀어러', mainStat: StatType.LUK },
  { name: '듀얼마스터', mainStat: StatType.LUK },
  { name: '슬래셔', mainStat: StatType.LUK },
  { name: '듀얼블레이더', mainStat: StatType.LUK },
  { name: '해적', mainStat: StatType.STR },
  { name: '인파이터', mainStat: StatType.STR },
  { name: '건슬링어', mainStat: StatType.DEX },
  { name: '캐논슈터', mainStat: StatType.STR },
  { name: '버커니어', mainStat: StatType.STR },
  { name: '발키리', mainStat: StatType.DEX },
  { name: '캐논블래스터', mainStat: StatType.STR },
  { name: '바이퍼', mainStat: StatType.STR },
  { name: '캡틴', mainStat: StatType.DEX },
  { name: '캐논마스터', mainStat: StatType.STR },
  { name: '노블레스', mainStat: StatType.NULL },
  { name: '소울마스터', mainStat: StatType.STR },
  { name: '플레임위자드', mainStat: StatType.INT },
  { name: '윈드브레이커', mainStat: StatType.DEX },
  { name: '나이트워커', mainStat: StatType.LUK },
  { name: '스트라이커', mainStat: StatType.STR },
  { name: '미하일', mainStat: StatType.STR },
  { name: '아란', mainStat: StatType.STR },
  { name: '에반', mainStat: StatType.INT },
  { name: '시티즌', mainStat: StatType.NULL },
  { name: '배틀메이지', mainStat: StatType.INT },
  { name: '와일드헌터', mainStat: StatType.DEX },
  { name: '메카닉', mainStat: StatType.DEX },
  { name: '데몬슬레이어', mainStat: StatType.STR },
  { name: '데몬어벤져', mainStat: StatType.HP },
  { name: '제논', mainStat: StatType.XENON },
  { name: '블래스터', mainStat: StatType.STR },
  { name: '메르세데스', mainStat: StatType.DEX },
  { name: '팬텀', mainStat: StatType.LUK },
  { name: '루미너스', mainStat: StatType.INT },
  { name: '카이저', mainStat: StatType.STR },
  { name: '엔젤릭버스터', mainStat: StatType.DEX },
  { name: '제로', mainStat: StatType.STR },
  { name: '은월', mainStat: StatType.STR },
  { name: '키네시스', mainStat: StatType.INT },
  { name: '카데나', mainStat: StatType.LUK },
  { name: '일리움', mainStat: StatType.INT },
  { name: '아크', mainStat: StatType.STR },
  { name: '호영', mainStat: StatType.LUK },
  { name: '아델', mainStat: StatType.STR },
  { name: '카인', mainStat: StatType.DEX },
];
