/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      typography: ({ theme }) => ({
        editor: {
          css: {
            '--tw-prose-body': 'var(--color-black-800)',
            '--tw-prose-headings': 'var(--color-black-800)',
            '--tw-prose-lead': 'var(--color-black-800)',
            '--tw-prose-links': 'var(--color-brand)',
            '--tw-prose-bold': 'var(--color-black-800)',
            '--tw-prose-counters': 'var(--color-black-800)',
            '--tw-prose-bullets': 'var(--color-black-800)',
            '--tw-prose-hr': 'var(--color-black-800)',
            '--tw-prose-quotes': 'var(--color-black-800)',
            '--tw-prose-quote-borders': 'var(--color-black-800)',
            '--tw-prose-captions': 'var(--color-black-800)',
            '--tw-prose-code': 'var(--color-black-800)',
            '--tw-prose-pre-code': 'var(--color-black-800)',
            '--tw-prose-pre-bg': 'var(--color-grey-300)',
            '--tw-prose-th-borders': 'var(--color-black-800)',
            '--tw-prose-td-borders': 'var(--color-black-800)',
            '--tw-prose-invert-body': 'var(--color-white-900)',
            '--tw-prose-invert-headings': 'var(--color-white-900)',
            '--tw-prose-invert-lead': 'var(--color-white-900)',
            '--tw-prose-invert-links': 'var(--color-dark-brand)',
            '--tw-prose-invert-bold': 'var(--color-white-900)',
            '--tw-prose-invert-counters': 'var(--color-white-900)',
            '--tw-prose-invert-bullets': 'var(--color-white-900)',
            '--tw-prose-invert-hr': 'var(--color-white-900)',
            '--tw-prose-invert-quotes': 'var(--color-white-900)',
            '--tw-prose-invert-quote-borders': 'var(--color-white-900)',
            '--tw-prose-invert-captions': 'var(--color-white-900)',
            '--tw-prose-invert-code': 'var(--color-white-900)',
            '--tw-prose-invert-pre-code': 'var(--color-white-900)',
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': 'var(--color-white-900)',
            '--tw-prose-invert-td-borders': 'var(--color-white-900)',
          },
        },
      }),
    },
  },
};
